name: iOS Visual Tests (Argos)

on:
  push:
    branches: [visual_test_clean_final]
  pull_request:

jobs:
  ios-visual-tests:
    runs-on: macos-latest

    env:
      IOS_APP_PATH: ./app/HowWeFeelMoodmeter.app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

    #   - name: Download iOS App
    #     run: |
    #       curl -L -o app.zip https://github.com/Rodrigomoll/HWFAutomation/releases/download/ios-app/HowWeFeelMoodmeter.app.zip
    #       unzip app.zip -d app
    #       ls -R app

    #   - name: Boot stable simulator
    #     run: |
    #       xcrun simctl shutdown all || true
    #       xcrun simctl erase all || true
    #       xcrun simctl boot "iPhone 16"
    #       xcrun simctl bootstatus "iPhone 16" -b
    #       sleep 20

    #   - name: Run iOS Visual Test
    #     run: npm run ios:skip

      - name: Upload screenshots to Argos
        run: npm exec -- argos upload --token ${{ secrets.ARGOS_TOKEN }} screenshots